### PR TITLE
Add docker support

### PR DESCRIPTION
**Pull request by isaqueprofeta**
Thank you very much for the project! Great tool!

I'd like to contribute some few lines with docker support, running an Alpine Nginx container in 8080 local machine port.

Hope it helps, and any question, please ask!

### CODE REVIEW

**Comment by jonmagic** [comment]
@isaqueprofeta hi, thanks for the contribution! Could you tell me a bit more about why you want to run it inside of docker? My instinct is to just update the README with instructions to clone the project and open the html file, I'm not sure what adding the container helps with. Also this is mostly just meant to act as a demo for folks to cope the javascript from :smile:

Cheers 🍻

**Comment by isaqueprofeta** [comment]
Jon, thinking that way, I'm just think that containers are easier to maintain and use. Better than always having a html inside a downloaded folder, I just do a "docker run", use it and kill it later.

Even better idea, if you have it published in dockerhub, you don't even need to clone or build it.

`docker run -p 8080:80 jonmagic/copy-excel-paste-markdown`

Would be beautiful. Hehe.

**Comment by jonmagic** [comment]
@isaqueprofeta I actually want folks to download the code in this repo, try it out locally, and even modify it before copying it into their project. Again, I appreciate the contribution but I don't think I want to add it to this particular project. Cheers :beers:

**Comment by isaqueprofeta** [comment]
Sure! No problem! Thx for the project again!

**Pull request closed without merging**
